version: '3'
services:
  frontend:
    build: ./FrontendAPI/
    ports:
      - 5000:80
    depends_on:
      - backend
  backend:
    build: ./BackendAPI/
    ports:
      - 5002:80
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment: 
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"